# Generated by Django 6.0.6 on 2026-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Roll_Number',
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
